% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabularx}
\usepackage{xltabular}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Final Project - Applied Statistics for Engineering and Scientists II},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Final Project - Applied Statistics for Engineering and Scientists
II}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Group 6}
\author{}
\date{\vspace{-2.5em}2026-08-22}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\newpage

\section{Part I - Concrete Compressive
Strength}\label{part-i---concrete-compressive-strength}

\subsection{Exploratory Data Analysis}\label{exploratory-data-analysis}

\textbf{Variable Description}

The Concrete Compressive Strength dataset describes concrete mixtures
based on their material composition and age. The objective is to explain
and predict concrete compressive strength, which represents the amount
of compressive load the concrete can withstand before failure.

\begin{itemize}
\item
  \textbf{Cement:} Amount of cement in the concrete mixture (kg/m³).
\item
  \textbf{BlastFurnaceSlag:} Amount of blast-furnace slag in the mixture
  (kg/m³).
\item
  \textbf{FlyAsh:} Amount of fly ash in the mixture (kg/m³).
\item
  \textbf{Water:} Amount of water used in the mixture (kg/m³).
\item
  \textbf{Superplasticizer:} Amount of superplasticizer used in the
  mixture (kg/m³).
\item
  \textbf{CoarseAggregate:} Amount of coarse aggregate, such as gravel
  or crushed stone (kg/m³).
\item
  \textbf{FineAggregate:} Amount of fine aggregate, typically sand
  (kg/m³).
\item
  \textbf{Age:} Age of the concrete at the time of strength measurement,
  measured in days.
\item
  \textbf{Strength:} Concrete compressive strength measured in MPa. This
  is the response variable to be predicted.
\end{itemize}

\begin{verbatim}
## Dimension: 1030 x 9 | Total missing values: 0
\end{verbatim}

The dataset contains 1,030 observations and 9 numerical variables,
consisting of eight predictors and one continuous response variable,
concrete compressive strength. No missing values were detected in any
variable, so no missing-value imputation is required.

\textbf{Distribution and Potential Outliers}

\begin{itemize}
\item
  \textbf{Age} is strongly right-skewed and contains several unusually
  large observations, suggesting that a transformation may be worth
  investigating.
\item
  \textbf{BlastFurnaceSlag} and \textbf{Superplasticizer} are strongly
  right-skewed with many zero values. These zeros likely represent
  mixtures where the ingredient was not used rather than missing data.
\item
  \textbf{FlyAsh} also has a large concentration at zero, with a
  right-skewed distribution among the positive observations.
\item
  \textbf{Water} contains a few potential low and high outliers, while
  \textbf{FineAggregate} has one potential high outlier.
\item
  \textbf{Strength} is moderately right-skewed with a small number of
  unusually high strength observations.
\item
  \textbf{Cement} and \textbf{CoarseAggregate} have relatively balanced
  distributions with no obvious extreme outliers.
\item
  Potential outliers identified from the boxplots are not automatically
  removed; their validity will be investigated during the data-cleaning
  stage.
\end{itemize}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/Distribution overview for report-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/Distribution overview for report-2.pdf}}

\textbf{Pairwise Relationships}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/pair wise-1.pdf}}

\begin{itemize}
\item
  \textbf{Cement} shows a clear positive and approximately linear
  relationship with Strength.
\item
  \textbf{Age} exhibits pronounced nonlinearity, with Strength
  increasing rapidly at early ages and then levelling off; therefore, a
  log transformation of Age will be investigated.
\item
  \textbf{Superplasticizer} shows a positive but mildly nonlinear
  association, while \textbf{Water} displays substantial curvature.
\item
  \textbf{BlastFurnaceSlag, FlyAsh, CoarseAggregate,} and
  \textbf{FineAggregate} show weaker marginal relationships with
  Strength.
\item
  Overall, the plots suggest that a purely linear specification may not
  fully capture all predictor-response relationships. These marginal
  plots are used to motivate further transformation checks.
\end{itemize}

\textbf{Correlation Analysis}

\begin{verbatim}
##                         Predictor Correlation_with_Strength
## Cement                     Cement                      0.50
## BlastFurnaceSlag BlastFurnaceSlag                      0.13
## FlyAsh                     FlyAsh                     -0.11
## Water                       Water                     -0.29
## Superplasticizer Superplasticizer                      0.37
## CoarseAggregate   CoarseAggregate                     -0.16
## FineAggregate       FineAggregate                     -0.17
## Age                           Age                      0.33
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/correlation 2-1.pdf}}

\begin{itemize}
\item
  \textbf{Cement} has the strongest positive linear correlation with
  Strength (\(r = 0.50\)).
\item
  \textbf{Superplasticizer} (\(r = 0.37\)) and \textbf{Age}
  (\(r = 0.33\)) also show positive linear associations with Strength.
\item
  \textbf{Water} has a negative correlation with Strength
  (\(r = -0.29\)), indicating that higher water content tends to be
  associated with lower compressive strength.
\item
  \textbf{FlyAsh}, \textbf{CoarseAggregate}, \textbf{FineAggregate}, and
  \textbf{BlastFurnaceSlag} show relatively weak linear correlations
  with Strength.
\item
  Among the predictors, the strongest pairwise correlation is between
  \textbf{Water} and \textbf{Superplasticizer} (\(r = -0.66\)),
  suggesting some potential collinearity.
\item
  No predictor pair has an absolute correlation greater than \(0.70\),
  so there is no evidence of severe pairwise multicollinearity at this
  stage.
\end{itemize}

\subsection{Data Cleaning}\label{data-cleaning}

\begin{verbatim}
##           Variable Lower_Bound Upper_Bound Number_of_Outliers Percentage
## 1           Cement      -52.54      605.92                  0       0.00
## 2 BlastFurnaceSlag     -213.75      356.25                  1       0.12
## 3           FlyAsh     -177.28      295.47                  0       0.00
## 4            Water      124.25      232.65                  7       0.85
## 5 Superplasticizer      -15.24       25.40                  5       0.61
## 6  CoarseAggregate      785.90     1175.50                  0       0.00
## 7    FineAggregate      583.75      968.15                  2       0.24
## 8              Age      -66.50      129.50                 43       5.22
## 9         Strength      -10.08       79.98                  3       0.36
\end{verbatim}

\begin{itemize}
\item
  Potential outliers were identified from the training set using the
  \(1.5\times IQR\) rule.
\item
  Most variables contained very few flagged observations. Water,
  Superplasticizer, FineAggregate, BlastFurnaceSlag, and Strength each
  had less than 1\% of observations outside the IQR bounds.
\item
  \textbf{Age} had the largest number of flagged observations (43
  observations, 5.22\%). However, its strongly right-skewed distribution
  suggests that these points mainly represent the upper tail of the age
  distribution rather than obvious data errors.
\item
  The flagged observations were retained because no clear evidence
  indicated measurement or data-entry errors. Removing valid extreme
  concrete mixtures could discard useful information and bias the
  subsequent models.
\item
  The skewness of Age will instead be addressed by investigating a log
  transformation.
\end{itemize}

\textbf{Variable Transformation}

\begin{verbatim}
## Warning: package 'patchwork' was built under R version 4.6.1
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/transformation-check-1.pdf}}

\begin{verbatim}
##       Form Correlation_with_Strength
## 1      Age                 0.3383149
## 2 log(Age)                 0.5584688
\end{verbatim}

\begin{itemize}
\item
  \textbf{Age} was strongly right-skewed and showed a pronounced
  nonlinear relationship with Strength. After applying a logarithmic
  transformation, the relationship became substantially more linear and
  the Pearson correlation increased from \(r = 0.338\) to \(r = 0.558\).
  Therefore, \texttt{log(Age)} was used in subsequent modelling.
\item
  \textbf{Cement, Water, FlyAsh, BlastFurnaceSlag, Superplasticizer,
  CoarseAggregate,} and \textbf{FineAggregate} were otherwise retained
  on their original scales because there was insufficient evidence that
  transformation would improve the modelling relationship.
\item
  \textbf{Strength} was retained on its original MPa scale to preserve
  direct interpretation of predictions and evaluation metrics.
\item
  All original predictors are numeric, so no categorical encoding was
  required.
\end{itemize}

\textbf{Feature Engineering}

\begin{itemize}
\item
  Zero values in BlastFurnaceSlag, FlyAsh, and Superplasticizer indicate
  ingredient absence, so binary presence indicators were added while
  retaining the original dosage variables, allowing the models to
  distinguish between ingredient presence and dosage.
\item
  A quadratic term, \(Water^2\), was added because the EDA, thêm figure
  cite, suggested curvature in the relationship between Water and
  concrete strength.
\end{itemize}

\subsection{Feature Selection}\label{feature-selection}

\textbf{Variance Inflation Factor (VIF)} screening and stepwise
selection were used as selection methods in this section for the
following reasons:

\begin{itemize}
\item
  Although most pairwise correlations among predictors are low
  (\(|r∣<0.45\), except \(r(Water, Superplasticizer)=−0.66\)). However,
  pairwise correlation alone may not capture multicollinearity involving
  multiple predictors. Therefore, VIF is needed to to assess the
  multicollinearity level of the predictors.
\item
  VIF only assesses multicollinearity and does not determine which
  predictors should be retained in the final model. Therefore, stepwise
  selection is also used to identify a more parsimonious set of
  predictors based on model fit and complexity.
\end{itemize}

\begin{table}[!h]
\centering
\caption{\label{tab:vif}Variance Inflation Factor (VIF) of Candidate Predictors}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lccc}
\toprule
\textbf{ } & \textbf{Predictor} & \textbf{VIF} & \textbf{Assessment}\\
\midrule
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{Water} & \cellcolor{gray!10}{187.87} & \cellcolor{gray!10}{Very High}\\
9 & Water2 & 186.70 & Very High\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{FlyAsh} & \cellcolor{gray!10}{15.94} & \cellcolor{gray!10}{Very High}\\
2 & BlastFurnaceSlag & 10.57 & Very High\\
\cellcolor{gray!10}{11} & \cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{10.55} & \cellcolor{gray!10}{Very High}\\
\addlinespace
1 & Cement & 8.05 & High\\
\cellcolor{gray!10}{7} & \cellcolor{gray!10}{FineAggregate} & \cellcolor{gray!10}{7.58} & \cellcolor{gray!10}{High}\\
6 & CoarseAggregate & 5.57 & High\\
\cellcolor{gray!10}{12} & \cellcolor{gray!10}{SuperplasticizerPresent} & \cellcolor{gray!10}{5.13} & \cellcolor{gray!10}{High}\\
5 & Superplasticizer & 5.08 & High\\
\addlinespace
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{SlagPresent} & \cellcolor{gray!10}{3.41} & \cellcolor{gray!10}{Acceptable}\\
8 & LogAge & 1.08 & Acceptable\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\item
  The VIF results indicate that \textbf{LogAge} (1.08) and
  \textbf{SlagPresent} (3.41) have acceptable levels of
  multicollinearity, while several other predictors show high VIF
  values. In particular, \textbf{Water} (187.87) and \textbf{Water2}
  (186.70) have extremely high VIFs because \textbf{Water2} is directly
  derived from \textbf{Water}, creating strong dependence between the
  polynomial terms.
\item
  High VIFs are also observed for \textbf{FlyAsh},
  \textbf{BlastFurnaceSlag}, and their presence indicators. This is
  expected in the results because the continuous variables and binary
  indicators capture related but distinct information: ingredient dosage
  and ingredient presence/absence, respectively.
\end{itemize}

\section{Stepwise selection}\label{stepwise-selection}

\begin{table}[!h]
\centering
\caption{\label{tab:stepwise}Feature Selection Results from Stepwise AIC}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{Predictor} & \textbf{Selected}\\
\midrule
\cellcolor{gray!10}{Cement} & \cellcolor{gray!10}{Yes}\\
BlastFurnaceSlag & Yes\\
\cellcolor{gray!10}{FlyAsh} & \cellcolor{gray!10}{Yes}\\
Water & Yes\\
\cellcolor{gray!10}{Superplasticizer} & \cellcolor{gray!10}{Yes}\\
\addlinespace
CoarseAggregate & Yes\\
\cellcolor{gray!10}{FineAggregate} & \cellcolor{gray!10}{Yes}\\
LogAge & Yes\\
\cellcolor{gray!10}{Water2} & \cellcolor{gray!10}{Yes}\\
SlagPresent & No\\
\addlinespace
\cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{Yes}\\
SuperplasticizerPresent & Yes\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\item
  Despite the high VIF values observed for several predictors, stepwise
  AIC retained most of them because removing these variables would
  reduce model complexity but lead to a poorer model fit.
\item
  In contrast, \textbf{SlagPresent} was excluded despite having an
  acceptable VIF (3.41), indicating that its exclusion was not driven by
  multicollinearity but by its limited contribution to the overall model
  fit. This may also be explained by the presence of
  \textbf{BlastFurnaceSlag}, which already captures the dosage
  information of the same ingredient.
\item
  The remaining presence indicators, \textbf{FlyAshPresent} and
  \textbf{SuperplasticizerPresent}, were retained, suggesting that they
  provided additional information beyond their corresponding continuous
  dosage variables.
\item
  Therefore, \textbf{SlagPresent} was removed from the model, while the
  other selected predictors were retained.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train\_clean }\OtherTok{\textless{}{-}}\NormalTok{ train\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{SlagPresent)}

\NormalTok{test\_clean }\OtherTok{\textless{}{-}}\NormalTok{ test\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{SlagPresent)}

\NormalTok{clean\_predictors }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}
  \FunctionTok{names}\NormalTok{(train\_clean),}
\NormalTok{  response}
\NormalTok{)}

\NormalTok{x\_train\_raw }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}
\NormalTok{  train\_clean[, clean\_predictors, }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{]}
\NormalTok{)}

\NormalTok{x\_test\_raw }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}
\NormalTok{  test\_clean[, clean\_predictors, }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{]}
\NormalTok{)}

\NormalTok{y\_train }\OtherTok{\textless{}{-}}\NormalTok{ train\_clean[[response]]}
\NormalTok{y\_test }\OtherTok{\textless{}{-}}\NormalTok{ test\_clean[[response]]}
\end{Highlighting}
\end{Shaded}

\subsection{Modeling with
Regularization}\label{modeling-with-regularization}

The Linear Regression was considered as the baseline model and apply
Ridge, Lasso, and Elastic Net as regularized alternatives in this
section for the following purposes:

\begin{itemize}
\item
  Linear Regression: Used as the baseline model to provide a reference
  for evaluating the regularized models.
\item
  Ridge Regression: Used to reduce the impact of multicollinearity by
  shrinking correlated predictors' coefficients without removing
  variables.
\item
  Lasso Regression: Used for automatic variable selection by shrinking
  some coefficients exactly to zero.
\item
  Elastic Net: Used to combine Ridge's stability with Lasso's variable
  selection, especially for correlated predictors.
\end{itemize}

\subsubsection{Linear Regression}\label{linear-regression}

\begin{table}[!h]
\centering
\caption{\label{tab:linear}OLS Baseline Model Coefficients}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{ccc}
\toprule
\textbf{Predictor} & \textbf{Coefficient} & \textbf{P\_value}\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{35.8695} & \cellcolor{gray!10}{< 0.001}\\
Cement & 13.3458 & < 0.001\\
\cellcolor{gray!10}{BlastFurnaceSlag} & \cellcolor{gray!10}{9.1976} & \cellcolor{gray!10}{< 0.001}\\
FlyAsh & 2.1530 & 0.0224\\
\cellcolor{gray!10}{Water} & \cellcolor{gray!10}{-12.3668} & \cellcolor{gray!10}{< 0.001}\\
\addlinespace
Superplasticizer & -1.8410 & < 0.001\\
\cellcolor{gray!10}{CoarseAggregate} & \cellcolor{gray!10}{1.9263} & \cellcolor{gray!10}{< 0.001}\\
FineAggregate & 2.3408 & < 0.001\\
\cellcolor{gray!10}{LogAge} & \cellcolor{gray!10}{10.2485} & \cellcolor{gray!10}{< 0.001}\\
Water2 & 9.0613 & 0.0034\\
\addlinespace
\cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{1.7840} & \cellcolor{gray!10}{0.0186}\\
SuperplasticizerPresent & 3.6568 & < 0.001\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  All predictors have p\textless0.05, indicating statistically
  significant associations with Strength conditional on the other
  predictors. The relatively high VIF values, particularly for
  \textbf{Water} and \textbf{Water2}, should be considered when
  interpreting individual coefficients because multicollinearity can
  make coefficient estimates less stable.
\end{itemize}

\subsubsection{Ridge regression}\label{ridge-regression}

\begin{table}[!h]
\centering
\caption{\label{tab:ridge}Ridge Regression Coefficients}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{Predictor} & \textbf{Coefficient}\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{33.5491}\\
Cement & 0.0867\\
\cellcolor{gray!10}{BlastFurnaceSlag} & \cellcolor{gray!10}{0.0592}\\
FlyAsh & -0.0134\\
\cellcolor{gray!10}{Water} & \cellcolor{gray!10}{-0.1475}\\
\addlinespace
Superplasticizer & -0.1066\\
\cellcolor{gray!10}{CoarseAggregate} & \cellcolor{gray!10}{-0.0087}\\
FineAggregate & -0.0146\\
\cellcolor{gray!10}{LogAge} & \cellcolor{gray!10}{8.0877}\\
Water2 & -0.0003\\
\addlinespace
\cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{2.5448}\\
SuperplasticizerPresent & 6.8236\\
\bottomrule
\end{tabular}
\end{table}

Compared with OLS, Ridge substantially shrinks the coefficients of
several predictors, especially the highly collinear variables
\textbf{Water}, \textbf{Water2}, \textbf{FlyAsh}, and
\textbf{BlastFurnaceSlag}. Other continuous predictors, including
\textbf{Cement}, \textbf{CoarseAggregate}, \textbf{FineAggregate}, and
\textbf{Superplasticizer}, are also strongly reduced. Meanwhile, larger
coefficients are retained for \textbf{FlyAshPresent}, and
\textbf{SuperplasticizerPresent}. This indicates a redistribution of
predictive contribution among correlated variables, which helps Ridge
reduce the impact of multicollinearity.

\subsubsection{Lasso regression}\label{lasso-regression}

\begin{table}[!h]
\centering
\caption{\label{tab:lasso}Lasso Regression Coefficients}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{Predictor} & \textbf{Coefficient}\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{-25.0561}\\
Cement & 0.1263\\
\cellcolor{gray!10}{BlastFurnaceSlag} & \cellcolor{gray!10}{0.1061}\\
FlyAsh & 0.0322\\
\cellcolor{gray!10}{Water} & \cellcolor{gray!10}{-0.5024}\\
\addlinespace
Superplasticizer & -0.3024\\
\cellcolor{gray!10}{CoarseAggregate} & \cellcolor{gray!10}{0.0233}\\
FineAggregate & 0.0276\\
\cellcolor{gray!10}{LogAge} & \cellcolor{gray!10}{8.6299}\\
Water2 & 0.0009\\
\addlinespace
\cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{3.6165}\\
SuperplasticizerPresent & 7.4926\\
\bottomrule
\end{tabular}
\end{table}

Compared with OLS, Lasso shrinks the coefficients of most predictors
toward zero, with the strongest shrinkage observed for \textbf{Water},
\textbf{Water2}, \textbf{FlyAsh}, \textbf{BlastFurnaceSlag}, and the
aggregate variables. However, no coefficient is reduced to zero, so all
predictors are retained in the model. Compared with Ridge, Lasso applies
slightly less shrinkage overall, while preserving the same signs of the
coefficients as OLS.

\subsubsection{Elastic Net regression}\label{elastic-net-regression}

\begin{verbatim}
##   alpha     lambda   cv_mse
## 2   0.2 0.00518238 47.64014
\end{verbatim}

\begin{table}[!h]
\centering
\caption{\label{tab:elastic-net}Elastic Net Regression Coefficients}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{Predictor} & \textbf{Coefficient}\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{-26.7288}\\
Cement & 0.1266\\
\cellcolor{gray!10}{BlastFurnaceSlag} & \cellcolor{gray!10}{0.1064}\\
FlyAsh & 0.0327\\
\cellcolor{gray!10}{Water} & \cellcolor{gray!10}{-0.4921}\\
\addlinespace
Superplasticizer & -0.3005\\
\cellcolor{gray!10}{CoarseAggregate} & \cellcolor{gray!10}{0.0236}\\
FineAggregate & 0.0279\\
\cellcolor{gray!10}{LogAge} & \cellcolor{gray!10}{8.6321}\\
Water2 & 0.0009\\
\addlinespace
\cellcolor{gray!10}{FlyAshPresent} & \cellcolor{gray!10}{3.6040}\\
SuperplasticizerPresent & 7.4810\\
\bottomrule
\end{tabular}
\end{table}

Although Elastic Net uses a relatively low alpha of 0.2, its coefficient
pattern is still similar to Lasso. Compared with OLS, most predictors
are shrunk toward zero, while \textbf{LogAge}, \textbf{FlyAshPresent},
and \textbf{SuperplasticizerPresent} retain relatively larger
coefficients. No predictor is eliminated, and the coefficient signs
remain unchanged. The overall shrinkage is slightly weaker than Lasso,
reflecting the combined L1 and L2 penalties in Elastic Net.

\subsection{Evaluation}\label{evaluation}

We use RMSE, MAE to evaluate the regression models in this section for
the following reasons:

\begin{itemize}
\tightlist
\item
  RMSE: Measures the average prediction error while giving greater
  weight to large errors, making it useful for detecting models with
  substantial prediction errors.
\item
  MAE: Measures the average absolute prediction error and provides an
  intuitive measure of the typical prediction error in the original
  response scale.
\end{itemize}

\begin{table}[!h]
\centering
\caption{\label{tab:evaluation}Test Set Performance Comparison}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{ccc}
\toprule
\textbf{Model} & \textbf{RMSE} & \textbf{MAE}\\
\midrule
\cellcolor{gray!10}{OLS} & \cellcolor{gray!10}{7.1021} & \cellcolor{gray!10}{5.6944}\\
Ridge & 7.2365 & 5.8099\\
\cellcolor{gray!10}{Lasso} & \cellcolor{gray!10}{7.0971} & \cellcolor{gray!10}{5.6942}\\
Elastic Net & 7.0974 & 5.6953\\
\bottomrule
\end{tabular}
\end{table}

All models are evaluated on the same held-out test set to ensure a fair
comparison. Lasso achieves the best performance, with the lowest RMSE of
7.0971 and MAE of 5.6942, followed very closely by Elastic Net and OLS.
The differences are very small, indicating that regularization provides
only a marginal improvement in generalization for this dataset.

The results also illustrate the bias--variance trade-off. OLS has no
regularization, resulting in low bias but potentially higher variance
due to multicollinearity. Lasso introduces regularization, slightly
increasing bias while reducing coefficient variance, which may explain
its marginally better test performance. Ridge produces the highest RMSE
and MAE, suggesting that its stronger shrinkage introduces more bias
than the reduction in variance can compensate for.

\section{Part II - ToothGrowth}\label{part-ii---toothgrowth}

\subsection{Dataset selection}\label{dataset-selection}

The built-in \texttt{ToothGrowth} dataset was selected because it
records a continuous response under every combination of two categorical
experimental factors. It contains odontoblast lengths for 60 guinea pigs
receiving vitamin C through orange juice (OJ) or ascorbic acid (VC) at
daily doses of 0.5, 1, or 2 mg. The six treatment combinations each
contain 10 observations, making the data suitable for a balanced
two-factor factorial analysis.

\subsection{Research question \&
hypotheses}\label{research-question-hypotheses}

The response variable is odontoblast length (\texttt{len}), in the
recorded units of the dataset. The two experimental factors are the
vitamin C delivery method (\texttt{supp}: orange juice, OJ, or ascorbic
acid, VC) and daily dose (\texttt{dose}: 0.5, 1, or 2 mg/day). Let
\(\mu_{ij}\) denote the population mean odontoblast length for
supplement \(i\) at dose \(j\). We use a significance level of
\(\alpha=0.05\) for all ANOVA tests.

The analysis addresses three related research questions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Supplement main effect:} Averaged across the three doses, does
  mean odontoblast length differ between OJ and VC?

  \begin{itemize}
  \tightlist
  \item
    \(H_{0,S}: \mu_{OJ,\cdot}=\mu_{VC,\cdot}\) (no supplement main
    effect).
  \item
    \(H_{A,S}: \mu_{OJ,\cdot}\ne\mu_{VC,\cdot}\).
  \end{itemize}
\item
  \textbf{Dose main effect:} Averaged across the two supplements, does
  mean odontoblast length differ among the three dose levels?

  \begin{itemize}
  \tightlist
  \item
    \(H_{0,D}: \mu_{\cdot,0.5}=\mu_{\cdot,1}=\mu_{\cdot,2}\) (no dose
    main effect).
  \item
    \(H_{A,D}:\) at least one marginal dose mean differs.
  \end{itemize}
\item
  \textbf{Supplement-by-dose interaction:} Does the effect of supplement
  on mean odontoblast length depend on dose?

  \begin{itemize}
  \tightlist
  \item
    \(H_{0,SD}: \mu_{OJ,j}-\mu_{VC,j}\) is the same for every dose \(j\)
    (no interaction).
  \item
    \(H_{A,SD}:\) at least one of these supplement differences changes
    with dose.
  \end{itemize}
\end{enumerate}

These hypotheses distinguish the overall effects of the two factors from
their interaction. This distinction is important because an overall
supplement difference can conceal different supplement effects at
individual doses.

\subsection{Descriptive statistics}\label{descriptive-statistics}

The following code computes both an overall summary and a summary for
every supplement--dose cell. Variance and standard deviation use the
usual sample definitions. The cell sample sizes also verify that the
design is balanced.

\begin{table}[!h]
\centering
\caption{\label{tab:toothgrowth-descriptive-tables}Overall Descriptive Statistics for Odontoblast Length}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{ccccccc}
\toprule
\textbf{N} & \textbf{Mean} & \textbf{Median} & \textbf{Variance} & \textbf{SD} & \textbf{Minimum} & \textbf{Maximum}\\
\midrule
\cellcolor{gray!10}{60} & \cellcolor{gray!10}{18.813} & \cellcolor{gray!10}{19.25} & \cellcolor{gray!10}{58.512} & \cellcolor{gray!10}{7.649} & \cellcolor{gray!10}{4.2} & \cellcolor{gray!10}{33.9}\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[!h]
\centering
\caption{\label{tab:toothgrowth-cell-summary}Odontoblast Length by Supplement and Dose}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{ccccccc}
\toprule
\textbf{Supplement} & \textbf{Dose} & \textbf{N} & \textbf{Mean} & \textbf{Median} & \textbf{Variance} & \textbf{SD}\\
\midrule
\cellcolor{gray!10}{OJ} & \cellcolor{gray!10}{0.5} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{13.23} & \cellcolor{gray!10}{12.25} & \cellcolor{gray!10}{19.889} & \cellcolor{gray!10}{4.460}\\
OJ & 1 & 10 & 22.70 & 23.45 & 15.296 & 3.911\\
\cellcolor{gray!10}{OJ} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{26.06} & \cellcolor{gray!10}{25.95} & \cellcolor{gray!10}{7.049} & \cellcolor{gray!10}{2.655}\\
VC & 0.5 & 10 & 7.98 & 7.15 & 7.544 & 2.747\\
\cellcolor{gray!10}{VC} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{16.77} & \cellcolor{gray!10}{16.50} & \cellcolor{gray!10}{6.327} & \cellcolor{gray!10}{2.515}\\
\addlinespace
VC & 2 & 10 & 26.14 & 25.95 & 23.018 & 4.798\\
\bottomrule
\end{tabular}
\end{table}

There are 60 observations and exactly 10 observations in each of the six
cells, so this is a balanced \(2\times3\) factorial design. Overall
odontoblast length has mean 18.813 and median 19.250 in the dataset's
recorded units. Mean odontoblast length rises with dose for both
supplements. For VC, the means at doses 0.5, 1, and 2 mg/day are 7.98,
16.77, and 26.14; for OJ, they are 13.23, 22.70, and 26.06. Thus, OJ has
a visibly higher mean at 0.5 and 1 mg/day, while the two supplement
means are almost identical at 2 mg/day. This convergence suggests that
an interaction may be present and should be tested formally.

The next plots show the distributions, group separation, and mean
response profiles from complementary perspectives.

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/toothgrowth-descriptive-plots-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/toothgrowth-descriptive-plots-2.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/toothgrowth-descriptive-plots-3.pdf}}

The box plots show a strong upward dose pattern for both delivery
methods. The interaction plot makes the convergence especially clear:
the OJ and VC profiles are separated at 0.5 and 1 mg/day but meet at 2
mg/day. The histograms show the raw response distribution for each
supplement; because each histogram pools the dose groups, their spread
reflects both within-dose variation and the strong shift in location
across doses.

\subsection{ANOVA/Factorial Design
Analysis}\label{anovafactorial-design-analysis}

\subsubsection{Choice of analysis
strategy}\label{choice-of-analysis-strategy}

Among the strategies we have learned, a \textbf{two-way factorial ANOVA
with interaction} is the appropriate choice. Both predictors are
experimentally defined categorical factors, all \(2\times3=6\) treatment
combinations are observed, the response is continuous, and the balanced
design has 10 observations per cell. The fitted model is

\[
Y_{ijk}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\varepsilon_{ijk},
\]

where \(\alpha_i\) is the supplement effect, \(\beta_j\) is the dose
effect, and \((\alpha\beta)_{ij}\) is their interaction.

A one-way completely randomized design using six combined treatment
labels could compare the six means, but it would not directly decompose
variation into supplement, dose, and interaction effects. The
unequal-sample-size strategy is unnecessary because every cell has the
same sample size. Fisher's LSD is a post-hoc comparison method rather
than the primary factorial model. ANCOVA would treat dose as a
quantitative covariate and impose a particular trend, whereas treating
the three assigned doses as a factor allows their means to differ
without assuming linearity. Finally, no blocking variable is recorded,
so this is a two-way factorial ANOVA rather than a randomized complete
block design.

\subsubsection{Result}\label{result}

\begin{table}[!h]
\centering
\caption{\label{tab:anova}ANOVA result}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cccccc}
\toprule
\textbf{Source} & \textbf{SS} & \textbf{df} & \textbf{MS} & \textbf{F} & \textbf{p.value}\\
\midrule
\cellcolor{gray!10}{supp} & \cellcolor{gray!10}{205.350} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{205.35000} & \cellcolor{gray!10}{15.571979} & \cellcolor{gray!10}{0.0002312}\\
dose & 2426.434 & 2 & 1213.21717 & 91.999965 & 0.0000000\\
\cellcolor{gray!10}{supp:dose} & \cellcolor{gray!10}{108.319} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{54.15950} & \cellcolor{gray!10}{4.106991} & \cellcolor{gray!10}{0.0218603}\\
Residuals & 712.106 & 54 & 13.18715 & NA & NA\\
\cellcolor{gray!10}{Total} & \cellcolor{gray!10}{3452.209} & \cellcolor{gray!10}{59} & \cellcolor{gray!10}{NA} & \cellcolor{gray!10}{NA} & \cellcolor{gray!10}{NA}\\
\bottomrule
\end{tabular}
\end{table}

The ANOVA results show that both supplement type and Vitamin C dose have
significant effects on tooth length, with p-values \[< 0.05\]. This
indicates that mean tooth length differs between the two supplement
types and among the different Vitamin C dose levels. Furthermore, the
interaction between supplement type and Vitamin C dose is also
significant (\[p<0.05\]), indicating that the effect of one factor on
tooth length depends on the level of the other factor. In particular,
the effect of Vitamin C dose on tooth length differs depending on
whether the supplement is administered as vitamin C (VC) or orange juice
(OJ).

The following partial eta-squared values supplement the significance
tests by measuring the size of each effect relative to that effect plus
the residual variation.

\begin{table}[!h]
\centering
\caption{\label{tab:toothgrowth-effect-sizes}Partial Eta-Squared Effect Sizes}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{Effect} & \textbf{Partial\_Eta\_Squared}\\
\midrule
\cellcolor{gray!10}{Supplement} & \cellcolor{gray!10}{NA}\\
Dose & 0.773\\
\cellcolor{gray!10}{Supplement x Dose} & \cellcolor{gray!10}{0.132}\\
\bottomrule
\end{tabular}
\end{table}

Dose has the largest partial eta-squared (0.773), indicating that it is
the dominant source of systematic variation in this experiment. Because
the interaction is significant, however, the supplement main effect is
only an average across dose levels and should not be interpreted as
showing that OJ is uniformly better than VC.

More specifically, the supplement effect is \(F(1,54)=15.572\) with
\(p=0.000231\); the marginal means are 20.663 for OJ and 16.963 for VC.
The dose effect is \(F(2,54)=92.000\) with \(p<0.0001\), and the
marginal means increase from 10.605 at 0.5 mg/day to 19.735 at 1 mg/day
and 26.100 at 2 mg/day. The interaction is \(F(2,54)=4.107\) with
\(p=0.0219\); the OJ-minus-VC mean difference is 5.25 at 0.5 mg/day,
5.93 at 1 mg/day, and \(-0.08\) at 2 mg/day. Thus, the observed OJ
advantage occurs at the two lower doses and is essentially absent at 2
mg/day.

\subsubsection{Model adequacy}\label{model-adequacy}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/anova adequacy-1.pdf}}

\begin{table}[!h]
\centering
\caption{\label{tab:anova adequacy}Result of Shapiro-Wilk Test}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{W} & \textbf{p\_value}\\
\midrule
\cellcolor{gray!10}{0.9849884} & \cellcolor{gray!10}{0.6694242}\\
\bottomrule
\end{tabular}
\end{table}

The normal Q-Q plot shows that the points are relatively close to the
reference line, suggesting that the residuals are approximately normally
distributed. Furthermore, the Shapiro-Wilk test, with the null
hypothesis that the residuals are normally distributed, produced a
p-value of \(0.6694\), so we fail to reject the null hypothesis.
Therefore, these results suggest that \textbf{the normality assumption
is satisfied}.

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/variance homogeneity-1.pdf}}

\begin{table}[!h]
\centering
\caption{\label{tab:variance homogeneity}Result of Levene's Test}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lccc}
\toprule
\textbf{ } & \textbf{Df} & \textbf{F value} & \textbf{Pr(>F)}\\
\midrule
\cellcolor{gray!10}{group} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{1.708578} & \cellcolor{gray!10}{0.1483606}\\
\bottomrule
\end{tabular}
\end{table}

By examining the residual plot, we observe that the residuals are
distributed around the reference line with a roughly equal vertical
spread across the fitted values, suggesting that the variances are
approximately constant. Furthermore, Levene's test, which has the null
hypothesis that all groups have equal variances, produces a p-value of
\(0.1484\). Since this p-value is greater than \(0.05\), we fail to
reject the null hypothesis. Therefore, these results suggest that
\textbf{the assumption of homogeneity of variance is satisfied}.

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/independence-1.pdf}}

\begin{verbatim}
## Warning: package 'lmtest' was built under R version 4.6.1
\end{verbatim}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## Warning: package 'zoo' was built under R version 4.6.1
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{table}[!h]
\centering
\caption{\label{tab:independence}Result of Durbin–Watson Test}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{cc}
\toprule
\textbf{DW} & \textbf{p\_value}\\
\midrule
\cellcolor{gray!10}{2.025437} & \cellcolor{gray!10}{0.2868449}\\
\bottomrule
\end{tabular}
\end{table}

When plotting residuals against observation order, the points are
randomly distributed around zero with no apparent systematic pattern,
suggesting that the residuals are independent. The Durbin--Watson test,
which has the null hypothesis that the residuals are independent, gives
a p-value of \[0.2868\]. Since \[p>0.05\], we fail to reject the null
hypothesis. Therefore, there is no significant evidence of
autocorrelation, \textbf{supporting the assumption of independence}.

\subsection{Post-hoc analysis}\label{post-hoc-analysis}

The ANOVA results indicate significant effects for both factors and
their interaction. However, since supplement type has only two levels,
there is no need for a post-hoc pairwise comparison for this factor.
Therefore, Tukey's HSD test will be performed for \textbf{dose} and for
the \textbf{combination of supplement type and dose}.

\subsubsection{Tukey's HSD on dose}\label{tukeys-hsd-on-dose}

\begin{table}[!h]
\centering
\caption{\label{tab:HSD on dose}Resutls of Tukey's HSD on Dose}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lccccc}
\toprule
\textbf{ } & \textbf{diff} & \textbf{lwr} & \textbf{upr} & \textbf{p adj} & \textbf{diff\_mean}\\
\midrule
\cellcolor{gray!10}{1-0.5} & \cellcolor{gray!10}{9.130} & \cellcolor{gray!10}{6.362488} & \cellcolor{gray!10}{11.897512} & \cellcolor{gray!10}{0.0e+00} & \cellcolor{gray!10}{0.4852941}\\
2-0.5 & 15.495 & 12.727488 & 18.262512 & 0.0e+00 & 0.8236180\\
\cellcolor{gray!10}{2-1} & \cellcolor{gray!10}{6.365} & \cellcolor{gray!10}{3.597488} & \cellcolor{gray!10}{9.132513} & \cellcolor{gray!10}{2.7e-06} & \cellcolor{gray!10}{0.3383239}\\
\bottomrule
\end{tabular}
\end{table}

\[
\text{diff\_mean}
=
\frac{\text{diff}}
{\text{ mean of tooth length}}
\] The results show that all three pairwise comparisons have p-values
below \[0.05\], indicating that the differences between all dose levels
are statistically significant. Furthermore, since all differences in
means are positive, higher doses of Vitamin C are associated with
greater tooth length. Increasing the dose from 0.5 to 2 mg resulted in a
great increase of approximately \[0.824\] times the mean tooth length,
indicating a substantial effect of dose.

\subsubsection{Tukey's HSD on interaction between supplement type and
dose}\label{tukeys-hsd-on-interaction-between-supplement-type-and-dose}

\begin{table}[!h]
\centering
\caption{\label{tab:HSD on both}Results of Tukey's HSD on Interaction}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lccccc}
\toprule
\textbf{ } & \textbf{diff} & \textbf{lwr} & \textbf{upr} & \textbf{p adj} & \textbf{diff\_mean}\\
\midrule
\cellcolor{gray!10}{VC.0.5-OJ.0.5} & \cellcolor{gray!10}{-5.25} & \cellcolor{gray!10}{-10.048124} & \cellcolor{gray!10}{-0.4518762} & \cellcolor{gray!10}{0.0242521} & \cellcolor{gray!10}{-0.2790574}\\
OJ.1-OJ.0.5 & 9.47 & 4.671876 & 14.2681238 & 0.0000046 & 0.5033664\\
\cellcolor{gray!10}{VC.1-OJ.0.5} & \cellcolor{gray!10}{3.54} & \cellcolor{gray!10}{-1.258124} & \cellcolor{gray!10}{8.3381238} & \cellcolor{gray!10}{0.2640208} & \cellcolor{gray!10}{0.1881644}\\
OJ.2-OJ.0.5 & 12.83 & 8.031876 & 17.6281238 & 0.0000000 & 0.6819631\\
\cellcolor{gray!10}{VC.2-OJ.0.5} & \cellcolor{gray!10}{12.91} & \cellcolor{gray!10}{8.111876} & \cellcolor{gray!10}{17.7081238} & \cellcolor{gray!10}{0.0000000} & \cellcolor{gray!10}{0.6862155}\\
\addlinespace
OJ.1-VC.0.5 & 14.72 & 9.921876 & 19.5181238 & 0.0000000 & 0.7824238\\
\cellcolor{gray!10}{VC.1-VC.0.5} & \cellcolor{gray!10}{8.79} & \cellcolor{gray!10}{3.991876} & \cellcolor{gray!10}{13.5881238} & \cellcolor{gray!10}{0.0000210} & \cellcolor{gray!10}{0.4672218}\\
OJ.2-VC.0.5 & 18.08 & 13.281876 & 22.8781238 & 0.0000000 & 0.9610206\\
\cellcolor{gray!10}{VC.2-VC.0.5} & \cellcolor{gray!10}{18.16} & \cellcolor{gray!10}{13.361876} & \cellcolor{gray!10}{22.9581238} & \cellcolor{gray!10}{0.0000000} & \cellcolor{gray!10}{0.9652729}\\
VC.1-OJ.1 & -5.93 & -10.728124 & -1.1318762 & 0.0073930 & -0.3152020\\
\addlinespace
\cellcolor{gray!10}{OJ.2-OJ.1} & \cellcolor{gray!10}{3.36} & \cellcolor{gray!10}{-1.438124} & \cellcolor{gray!10}{8.1581238} & \cellcolor{gray!10}{0.3187361} & \cellcolor{gray!10}{0.1785967}\\
VC.2-OJ.1 & 3.44 & -1.358124 & 8.2381238 & 0.2936430 & 0.1828490\\
\cellcolor{gray!10}{OJ.2-VC.1} & \cellcolor{gray!10}{9.29} & \cellcolor{gray!10}{4.491876} & \cellcolor{gray!10}{14.0881238} & \cellcolor{gray!10}{0.0000069} & \cellcolor{gray!10}{0.4937987}\\
VC.2-VC.1 & 9.37 & 4.571876 & 14.1681238 & 0.0000058 & 0.4980510\\
\cellcolor{gray!10}{VC.2-OJ.2} & \cellcolor{gray!10}{0.08} & \cellcolor{gray!10}{-4.718124} & \cellcolor{gray!10}{4.8781238} & \cellcolor{gray!10}{1.0000000} & \cellcolor{gray!10}{0.0042523}\\
\bottomrule
\end{tabular}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{FinalStat2_files/FinalStat2_files/figure-latex/HSD on both-1.pdf}}
Except for the comparisons VC.1 vs OJ.0.5, OJ.2 vs OJ.1, VC.2 vs OJ.1,
and VC.2 vs OJ.2, all other pairwise comparisons are statistically
significant (\[p<0.05\]). The heatmap shows the mean difference in tooth
length between the group in each row and the group in each column, with
non-significant differences greyed out.

From the heatmap, we can observe that higher doses are generally
associated with greater tooth length. Additionally, supplementation with
orange juice tends to result in longer tooth length than vitamin C at
comparable doses. However, this trend is less consistent when there is a
large difference in dose, such as between 0.5 mg and 2 mg, where the
effect of dose appears to outweigh the effect of supplement type.

For orange juice supplementation, the variation in tooth length across
different doses is less pronounced than for ascorbic acid. In
particular, when the dose increases from 0.5 mg to 2 mg, ascorbic acid
produces a difference equivalent to \[0.97\] times the mean tooth
length, whereas orange juice produces a smaller difference of \[0.68\]
times the mean tooth length.

\subsection{Conclusion and Evaluation}\label{conclusion-and-evaluation}

The analysis provides evidence that odontoblast length depends on
vitamin C dose, supplement type, and their interaction. Dose is the
dominant factor: mean tooth length increases substantially as the dose
rises from 0.5 to 2 mg/day. OJ produces greater mean tooth length than
VC at the two lower doses, but the two delivery methods have almost
identical means at 2 mg/day. The significant interaction therefore shows
that the supplement effect must be interpreted at each dose rather than
as one constant overall advantage.

The post-hoc results support this interpretation. All marginal dose
comparisons are significant, while the treatment-combination comparisons
show that several supplement--dose groups are statistically
indistinguishable. In practical terms, increasing dose has a stronger
and more consistent relationship with tooth length than changing the
delivery method, especially when dose differences are large.

The factorial ANOVA is appropriate because the dataset is balanced and
contains all six combinations of the two categorical factors. The
residual diagnostics and formal tests provide no evidence against the
normality, equal-variance, or independence assumptions. Nevertheless,
these diagnostics have limited power with 10 observations per cell, and
the independence assumption ultimately depends on how the animals were
assigned and measured. The conclusions should therefore be restricted to
the dose levels, delivery methods, response measure, and study
population represented in \texttt{ToothGrowth}; they should not be
extrapolated to untested doses or broader populations without additional
evidence.

\end{document}
